

CREATE TABLE "Tipo_Rol" (
	"ID_TIPO_ROL"	INTEGER NOT NULL,
	"NOM_TIPO_ROL"	TEXT NOT NULL,
	PRIMARY KEY("ID_TIPO_ROL" AUTOINCREMENT)
);


CREATE TABLE "Productos_FJ" (
	"ID_PRODUCTO_FJ"	INTEGER NOT NULL,
	"NOMBRE_PRODUCTO_FJ"	TEXT NOT NULL,
	"VALOR_NETO_PRODUCTO_FJ"	INTEGER NOT NULL,
	"VALOR_IVA_PRODUCTO_FJ"	INTEGER NOT NULL,
	"VALOR_TOTAL_PRODUCTO_FJ"	INTEGER NOT NULL,
	"DES_ADICIONAL_PRODUCTO_FJ"	TEXT NOT NULL,
	"CATEGORIA_PRODUCTO_FJ"	TEXT NOT NULL,
	"STOCK_PRODUCTO_FJ"	INTEGER NOT NULL,
	"MARCA_PRODUCTO_FJ"	TEXT NOT NULL,
	PRIMARY KEY("ID_PRODUCTO_FJ" AUTOINCREMENT)
);

CREATE TABLE "Usuarios_FJ" (
	"ID_USUARIO_FJ"	INTEGER NOT NULL,
	"USUARIO_FJ"	TEXT,
	"NOMBRE_USUARIO_FJ"	TEXT NOT NULL,
	"APELLIDO_USUARIO_FJ"	TEXT NOT NULL,
	"MAIL_USUARIO_FJ"	TEXT NOT NULL,
	"PASS_USUARIO_FJ"	TEXT NOT NULL,
	"ROL_USUARIO_FJ"	INTEGER NOT NULL,
	PRIMARY KEY("ID_USUARIO_FJ" AUTOINCREMENT)
);

CREATE TABLE "Logs_FJ" (
	"ID_LOGS_FJ"	INTEGER NOT NULL,
	"FECHA_LOGS_FJ"	TEXT NOT NULL,
	"DESCRIPCION_LOGS_FJ"	TEXT NOT NULL,
	PRIMARY KEY("ID_LOGS_FJ" AUTOINCREMENT)
);



INSERT INTO Tipo_Rol (NOM_TIPO_ROL) VALUES ('Administrador');
INSERT INTO Tipo_Rol (NOM_TIPO_ROL) VALUES ('Cliente');


